# Права:

# freport.report - разрешение на использ. команды /report
# freport.reports - разрешение на использ. команды /reports
# freport.protection - защита от жалобы
# freport.info-report - получение информации о новых репортов на игроков
# freport.info-other - получение остальной информации со стороны действий админов


# Поддержка BungeeCord, true - если это плагин стоит на BungeeCord и Bukkit, false - если только на Bukkit
bungeecord_enable_plugin: false

mysql:
  host: 135.181.119.34
  username: aspect
  password: KsoM9XEVG3me0ET
  port: '3307'
  database: Reports

VK:
  peer: 2000000001
  server: "Тестовый"


# Задержка на команду /report
cooldown-report-command: '2m'


