# ██████╗░░█████╗░░██╗░░░░░░░██╗███╗░░██╗██╗░░░░░░█████╗░░█████╗░██████╗░███████╗██████╗░  ███████╗██████╗░░█████╗░███╗░░░███╗
# ██╔══██╗██╔══██╗░██║░░██╗░░██║████╗░██║██║░░░░░██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗  ██╔════╝██╔══██╗██╔══██╗████╗░████║
# ██║░░██║██║░░██║░╚██╗████╗██╔╝██╔██╗██║██║░░░░░██║░░██║███████║██║░░██║█████╗░░██║░░██║  █████╗░░██████╔╝██║░░██║██╔████╔██║
# ██║░░██║██║░░██║░░████╔═████║░██║╚████║██║░░░░░██║░░██║██╔══██║██║░░██║██╔══╝░░██║░░██║  ██╔══╝░░██╔══██╗██║░░██║██║╚██╔╝██║
# ██████╔╝╚█████╔╝░░╚██╔╝░╚██╔╝░██║░╚███║███████╗╚█████╔╝██║░░██║██████╔╝███████╗██████╔╝  ██║░░░░░██║░░██║╚█████╔╝██║░╚═╝░██║
# ╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚══╝╚══════╝░╚════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═════╝░  ╚═╝░░░░░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═╝
#
# ███╗░░░███╗██╗███╗░░██╗███████╗██╗░░░░░███████╗░█████╗░██╗░░██╗░░░██████╗░██████╗░░█████╗░
# ████╗░████║██║████╗░██║██╔════╝██║░░░░░██╔════╝██╔══██╗██║░██╔╝░░░██╔══██╗██╔══██╗██╔══██╗
# ██╔████╔██║██║██╔██╗██║█████╗░░██║░░░░░█████╗░░███████║█████═╝░░░░██████╔╝██████╔╝██║░░██║
# ██║╚██╔╝██║██║██║╚████║██╔══╝░░██║░░░░░██╔══╝░░██╔══██║██╔═██╗░░░░██╔═══╝░██╔══██╗██║░░██║
# ██║░╚═╝░██║██║██║░╚███║███████╗███████╗███████╗██║░░██║██║░╚██╗██╗██║░░░░░██║░░██║╚█████╔╝
# ╚═╝░░░░░╚═╝╚═╝╚═╝░░╚══╝╚══════╝╚══════╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░░░░╚═╝░░╚═╝░╚════╝░
#
# Права:

# magmareports.report - разрешение на использ. команды /report
# magmareports.reports - разрешение на использ. команды /reports
# magmareports.protection - защита от жалобы
# magmareports.info-report - получение информации о новых репортов на игроков
# magmareports.info-other - получение остальной информации со стороны действий админов


# Поддержка BungeeCord, true - если это плагин стоит на BungeeCord и Bukkit, false - если только на Bukkit
bungeecord_enable_plugin: false

mysql:
  host: '95.216.9.177'
  username: 'denis'
  password: 'kITi4InEG6nILa7oKaBINe55m4t8YA'
  port: '1206'
  database: 'censure'


# Задержка на команду /report
cooldown-report-command: '2m'

# Сообщения
messages:
  serverVK: "Тестовый"
  no_permission: '&6[!] &fНедостаточно прав!'
  info_reports_player: '&6[!] &fИгрок &a{target} &fполучил &c{reports} &f- напишите &e(/reports, /rs)'
  usage_report_command: '&6[!] &f/report [ник] [причина] &a - подать жалобу на игрока'
  player_not_online: '&6[!] &fИгрок &c{target} &fне онлайн!'
  successful_send_report: '&6[!] &fВы успешно отправили репорт на игрока &c{target} &fпо причине: &a{reason}'
  teleport_player: '&6[!] &fВы успешно телепортировались к &c{target}'
  limit_reports: '&6[!] &fУ игрока &c{target} &fпревышен лимит жалоб!'
  cooldown_report_command: '&6[!] &fДля след. отправки репорта подождите &c{time}'
  sender_instanceof_player: '&6[!] &fВы не можете на самого себя подать репорт!'
  little_reason: '&6[!] &fУкажите длиннее причину репорта!'
  protection_player: '&6[!] &fВы не можете подать жалобу на данного игрока!'
  banned_player: '&6[!] &fАдминистратор &c{admin}&f наказал &a{target}'
  cancel_report_player: '&6[!] &fАдминистратор &c{admin}&f отклонил репорт на игрока &a{target}'

# Инвентари
inventory-list-reports:
  title: 'Жалобы | Страница {page}'
  item-close:
    name: '&c&l[Закрыть список]'
    lore:
      - ''
      - '&aНажмите сюда, чтобы закрыть список'
  item-next-page:
    name: '&aСледующая страница'
    lore:
      - '&7Нажмите для перехода'
      - '&7на {page} страницу'
  back-item-page:
    name: '&aПредыдущая страница'
    lore:
      - '&7Нажмите для перехода'
      - '&7на {page} страницу'
  item-stats:
    name: '&eСтатистика'
    lore:
      - ''
      - '&fВсего жалоб: &a{count}'
  reports-format: ' &r{prefix}{reporter}&f: &7{reason}'
  format-item-skull:
    name: '&eЖалоба на &r{prefix}{target}'
    lore:
      - ''
      - '&fПоследняя жалоба:'
      - '&e{time} назад'
      - ''
      - '&fВсего жалоб: &c{reports-count}'
      - ''
      - '&fСписок пожаловавшихся:'
      - '{reports}'
      - ''
      - '&aНажмите для действий'
inventory-ban-player:
  title: 'Блокировка {target}'
  back-item:
    name: '&eВернуться в профиль игрока'
    lore:
      - ''
      - '&aНажмите сюда, чтобы перейти в профиль игрока'
  bans:
    1:
      name: '&fБан &aнавсегда'
      punish: 'ban {target} Читы.'
      lore:
        - ''
        - '&eИспользование читов'
    2:
      name: '&fБан на &c1 час'
      punish: 'tempban {target} 1h Гриферство.'
      lore:
        - ''
        - '&eГриферство'
    3:
      name: '&fБан на &c2 час'
      punish: 'tempban {target} 2h Использование багов.'
      lore:
        - ''
        - '&eИспользование багов'
    4:
      name: '&fБан на &c3 час'
      punish: 'tempban {target} 3h Обман администрации.'
      lore:
        - ''
        - '&eОбман администрации'
    5:
      name: '&fБан &aнавсегда'
      punish: 'ban {target} Оск. администрации.'
      lore:
        - ''
        - '&eОск. администрации'
inventory-profile-player:
  title: '{target}'
  back-item:
    name: '&eВернуться в главное меню'
    lore:
      - ''
      - '&aНажмите сюда, чтобы перейти в главное меню'
  ban-item:
    name: '&dВыдать бан'
    lore:
      - ''
      - '&aНажмите сюда, чтобы выдать бан игроку'
  cancel-item:
    name: '&fОтклонить репорт'
    lore:
      - ''
      - '&aНажмите сюда, чтобы отклонить репорт'
  teleport-item:
    name: '&eТелепортироваться к &c{target}'
    status:
      online_player: '&aНажмите сюда, чтобы телепортироваться'
      offline_player: '&c&l[Телепортация недоступна, игрок оффлайн]'
    lore:
      - ''
      - '{status}'
  format-item-report:
    name: '&fРепорт #{number}'
    lore:
      - ''
      - '&7Время: &6{time} назад'
      - '&7Отправитель: &r{prefix}{reporter}'
      - '&7Причина: {reason}'